assets:
  allowed_extensions:
    # text formats
    txt: true
    css: true
    js: true
    # image formats
    jpg: true
    gif: true
    png: true
    wbmp: true
    xbm: true
    webp: true
    bmp: true
    ico: true
    svg: true
    # web fonts
    eot: true
    woff2: true
    woff: true
    ttf: true

images:
  driver: gd
  presets:
    default:
      fit: 1000
    full:
      fit: 1920
    thumbnail:
      crop: 144

cache:
  ttl:
    handle_request:   600      # output of handling a request
    content_provider: 10      # output of searches in content filesystem
    asset_provider:   60      # output of searches for assets
    dom_provider:     86400   # output of DOM processing

site:
  name: Unnamed site

twig_environment:
  cache: false

js:
  minify: false
  bundle: false

css:
  minify: false
  bundle: false
  max_inlined: 0

theme_variables:
  # sizing
  margin: 2rem
  padding: 1.5rem
  font-size: 1rem
  font-scaler: 1.2
  heading-font-scaler: 1.2
  heading-scale: 1.2
  line-height: 1.5em
  line-height-loose: 1.8em
  line-height-tight: 1.2em
  # colors
  color-primary: '#43A047'
  color-secondary: '#9E9D24'
  color-success: '#8BC34A'
  color-danger: '#f44336'
  color-warning: '#FF9800'
  color-info: '#00BCD4'
  # link colors
  color-a: ${theme_variables.text-primary}
  color-a-visited: ${theme_variables.text-secondary}
  color-a-focus: ${theme_variables.text-info}
  color-a-hover: ${theme_variables.text-info}
  color-a-active: ${theme_variables.text-success}
  color-dark-a: ${theme_variables.text-dark-primary}
  color-dark-a-visited: ${theme_variables.text-dark-secondary}
  color-dark-a-focus: ${theme_variables.text-dark-info}
  color-dark-a-hover: ${theme_variables.text-dark-info}
  color-dark-a-active: ${theme_variables.text-dark-success}
  # light mode
  text-normal: '#444'
  text-accent: '#000'
  text-primary: ${theme_variables.color-primary}
  text-secondary: ${theme_variables.color-secondary}
  text-success: ${theme_variables.color-success}
  text-danger: ${theme_variables.color-danger}
  text-warning: ${theme_variables.color-warning}
  text-info: ${theme_variables.color-info}
  text-muted: '#999'
  bg-normal: '#eee'
  bg-accent: '#fff'
  bg-primary: ${theme_variables.color-primary}
  bg-secondary: ${theme_variables.color-secondary}
  bg-success: ${theme_variables.color-success}
  bg-danger: ${theme_variables.color-danger}
  bg-warning: ${theme_variables.color-warning}
  bg-info: ${theme_variables.color-info}
  bg-muted: '#ddd'
  # dark mode
  text-dark-normal: '#ddd'
  text-dark-accent: '#eee'
  text-dark-primary: ${theme_variables.text-primary}
  text-dark-secondary: ${theme_variables.text-secondary}
  text-dark-success: ${theme_variables.text-success}
  text-dark-danger: ${theme_variables.text-danger}
  text-dark-warning: ${theme_variables.text-warning}
  text-dark-info: ${theme_variables.text-info}
  text-dark-muted: '#999'
  bg-dark-normal: '#333'
  bg-dark-accent: '#222'
  bg-dark-primary: ${theme_variables.bg-primary}
  bg-dark-secondary: ${theme_variables.bg-secondary}
  bg-dark-success: ${theme_variables.bg-success}
  bg-dark-danger: ${theme_variables.bg-danger}
  bg-dark-warning: ${theme_variables.bg-warning}
  bg-dark-info: ${theme_variables.bg-info}
  bg-dark-muted: '#555'
