assets:
  # These extensions may also potentially be fulfilled by the specified
  # additional extenions
  equivalent_extensions:
    css: [scss]
  # These extensions are allowed to be passed through as linked assets,
  # if no specific handlers have handled them.
  passthrough_extensions:
    txt: true
    css: true
    js: true
    woff: true
    woff2: true
    ttf: true
    eot: true
    svg: true