cache:
  directory: ${base_dir}/cache/
  ttl:
    content: 60
    pages: 600
    assets: 3600
  driver: filesystem
  driver_filesystem_config:
    encoder: Native
    path: ${cache.directory}CacheProvider
  driver_sqlite_config:
    path: ${cache.directory}CacheProvider
