site:
  url: 'https://localhost:8000/'

templates:
  site:
    name: Demo site

cache:
  driver: ephemeral
  directory: '${base_dir}/cache/'
  driver_filesystem_config:
    encoder: Native

assets:
  output:
    directory: '${base_dir}/assets/'
    url: '@/assets/'

statics:
  enabled: true
  directory: '${base_dir}'
  ttl: 60

theme:
  css:
    bundle: true
  js:
    bundle: true