site:
  url: 'http://localhost/leafcutter/web/'

templates:
  site:
    name: Demo site

cache:
  driver: ephemeral
  directory: '${base_dir}/cache/'
  driver_filesystem_config:
    encoder: Native

assets:
  output:
    directory: '${base_dir}/assets/'
    url: '@/assets/'

statics:
  enabled: false
  directory: '${base_dir}'
  ttl: 60

theme:
  css:
    bundle: false
    max_inlined: 0
    minify: false
  js:
    bundle: false
    minify: false
    inline_loader: false
